### ISSUE TITLE
Understand Database

### ISSUE THREAD

**Issue by allunamesrtaken123** [SimChid/comp-333-hw2#8]
We both need to read up on how to incorporate php database into our site, specifically the use of local databases in development.

**Comment by SimChid** [comment]
I was able to create a database, you should do the same. I'm also updating dbconnection.php to read the following:

$db = mysqli_connect("localhost","username","password","music_db");

<img width="972" alt="Screenshot 2023-10-13 at 10 05 29 AM" src="https://github.com/SimChid/comp-333-hw2/assets/144281352/1e4f7860-6c2c-4c6b-8782-8cb331061ece">

**Comment by allunamesrtaken123** [comment]
Nice! I couldn't figure out what it should be
